export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const NEW_QUESTIONS = 'NEW_QUESTIONS';
export const SAVE_ANSWER = 'SAVE_ANSWER';